# Generated by Django 5.0.1 on 2024-02-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('Продажа', 'Продажа'), ('Покупка', 'Покупка')], max_length=20)),
                ('car_type', models.CharField(choices=[('Легковые', 'Легковые'), ('Коммерческие', 'Коммерческие'), ('Спецтехника', 'Спецтехника'), ('Мото', 'Мото'), ('Запчасти', 'Запчасти'), ('Услуги', 'Услуги')], max_length=20)),
                ('make_and_model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('body_type', models.CharField(max_length=50)),
                ('generation', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('drive', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('modification', models.CharField(max_length=50)),
                ('steering_wheel', models.CharField(max_length=50)),
                ('buying', models.BooleanField(default=False)),
            ],
        ),
    ]
