# Generated by Django 5.0.1 on 2024-02-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_abs', '0002_remove_carad_ad_type_remove_carad_buying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='brand',
            field=models.CharField(default=1, max_length=255, verbose_name='Бренд'),
            preserve_default=False,
        ),
    ]
