# Generated by Django 5.0.1 on 2024-02-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_abs', '0003_carad_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
