# Generated by Django 5.0.2 on 2024-02-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_abs', '0005_remove_yourusermodel_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carad',
            name='additional_options',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='color',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='contact_region',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='external_options',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='interior_options',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='make_and_model',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='media_options',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='modification',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='price',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='safety_options',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='steering_wheel',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='wheel_drive',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='year',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
